### ISSUE TITLE
error

### ISSUE THREAD

**Issue by zhi3210happy** [duanguang/react-node-cms#2]
ERROR in ./client/common/libs/images/login-bg.jpg
    Module build failed: Error: Cannot find module 'file-loader'
        at Function.Module._resolveFilename (module.js:489:15)
        at Function.Module._load (module.js:439:25)
        at Module.require (module.js:517:17)
        at require (internal/module.js:11:18)
        at Object.module.exports (C:\Users\Administrator\Desktop\react-node-cms-master\node_modules\url-loader\index.js:29:22)
     @ ./~/css-loader!./~/less-loader!./client/src/container/admin/user/css/login.less 6:106-163

**Comment by duanguang** [comment]
node_modules 里面依赖文件不完整。你可以删掉，重新安装依赖试试
